contact/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
 
    path('', views.contactView, name='contact'),
    
    
]

contact2/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
 
    path('', views.contac2tView, name='contact2'),
    
    
]

likeshop/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.conf.urls import include
urlpatterns += [
    path('newitem/', include('newitem.urls')),
]

urlpatterns += [
    path('contact/', include('contact.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/contact/')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newitem/urls.py
from django.urls import path
from newitem import views


urlpatterns = [path('', views.index, name='index'),

]

contact/models.py
from django.db import models

class Price(models.Model):
    

    price = models.CharField(max_length=200, help_text="Enter price")
   
    

    def __str__(self):
        
        return self.price

class Oldprice(models.Model):
    
   
    oldprice = models.CharField(max_length=200, help_text="Enter old price")
   

    def __str__(self):
        
        return self.oldprice

class Discount(models.Model):
    
  
    discount = models.CharField(max_length=200, help_text="Enter a discount")

    def __str__(self):
        
        return self.discount

contact2/models.py
from django.db import models

class Price(models.Model):
    

    price = models.CharField(max_length=200, help_text="Enter price")
   
    

    def __str__(self):
        
        return self.price

class Oldprice(models.Model):
    
   
    oldprice = models.CharField(max_length=200, help_text="Enter old price")
   

    def __str__(self):
        
        return self.oldprice

class Discount(models.Model):
    
  
    discount = models.CharField(max_length=200, help_text="Enter a discount")

    def __str__(self):
        
        return self.discount

newitem/models.py
from django.db import models

class Price(models.Model):
    

    price = models.CharField(max_length=200, help_text="Enter price")
   
    

    def __str__(self):
        
        return self.price

class Oldprice(models.Model):
    
   
    oldprice = models.CharField(max_length=200, help_text="Enter old price")
   

    def __str__(self):
        
        return self.oldprice

class Discount(models.Model):
    
  
    discount = models.CharField(max_length=200, help_text="Enter a discount")

    def __str__(self):
        
        return self.discount

contact/forms.py
# Модель формы обратной связи
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)

contact2/forms.py
# Модель формы обратной связи
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)

contact/views.py
from django.shortcuts import render

from django.shortcuts import render
# -*- coding: utf-8 -*-
from django.http import HttpResponse
 
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError

from django import forms
class ContactForm(forms.Form):
    subject = forms.CharField(help_text="Введите своё имя", max_length=100, widget=forms.TextInput(attrs={'size':'30','class': 'name','placeholder':'Ваше имя'}))
    #sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'30','class': 'name','placeholder':'Телефон'}))
    copy = forms.BooleanField(required=False)



def contactView(request):

	if request.method == 'POST':
		form = ContactForm(request.POST)
		#Если форма заполнена корректно, сохраняем все введённые пользователем значения
		if form.is_valid():
			subject = form.cleaned_data['subject']
			#sender = form.cleaned_data['sender']
			message = form.cleaned_data['message']
			copy = form.cleaned_data['copy']

			recipients = ['tompipka@gmail.com']

			#Если пользователь захотел получить копию себе, добавляем его в список получателей
			if copy:
				recipients.append(sender)
			try:
				send_mail(subject, message, 'tompipka@gmail.com', recipients)
			except BadHeaderError: #Защита от уязвимости
				return HttpResponse('Invalid header found')
			#Переходим на другую страницу, если сообщение отправлено
			return render(request, 'templates/thanks.html')
	else:
		#Заполняем форму
		form = ContactForm()
	#Отправляем форму на страницу


	return render(request, 'templates/contact.html', {'form': form})






    

contact2/views.py
from django.shortcuts import render

from django.shortcuts import render
# -*- coding: utf-8 -*-
from django.http import HttpResponse
 
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError

from django import forms
class ContactForm(forms.Form):
    subject = forms.CharField(help_text="Введите своё имя", max_length=100, widget=forms.TextInput(attrs={'size':'30','class': 'name','placeholder':'Ваше имя'}))
    #sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'30','class': 'name','placeholder':'Телефон'}))
    copy = forms.BooleanField(required=False)



def contactView(request):

	if request.method == 'POST':
		form = ContactForm(request.POST)
		#Если форма заполнена корректно, сохраняем все введённые пользователем значения
		if form.is_valid():
			subject = form.cleaned_data['subject']
			#sender = form.cleaned_data['sender']
			message = form.cleaned_data['message']
			copy = form.cleaned_data['copy']

			recipients = ['tompipka@gmail.com']

			#Если пользователь захотел получить копию себе, добавляем его в список получателей
			if copy:
				recipients.append(sender)
			try:
				send_mail(subject, message, 'tompipka@gmail.com', recipients)
			except BadHeaderError: #Защита от уязвимости
				return HttpResponse('Invalid header found')
			#Переходим на другую страницу, если сообщение отправлено
			return render(request, 'templates/thanks.html')
	else:
		#Заполняем форму
		form = ContactForm()
	#Отправляем форму на страницу


	return render(request, 'base_generic.html', {'form': form})






    

newitem/views.py
from django.shortcuts import render
from .models import Price, Oldprice, Discount

def index(request):
    
    for prices in list(Price.objects.all()):
    	price = prices

    for oldprices in list(Oldprice.objects.all()):
    	oldprice = oldprices

    for discounts in list(Discount.objects.all()):
    	discount = discounts
  
    
    
    context = {
        'price': price,
        'oldprice': oldprice,
        'discount': discount,
        
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)






    

newitem/templates/base_generic.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  
  
  {% load static %} {% load staticfiles%}
  
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-127165440-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-127165440-1');
</script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Автопроектор</title>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  

  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    
     <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
     <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css" />
     <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>

</head>

<body>

  <header>
    
    <nav>
      <li><a href="#info">ХАРАКТЕРИСТИКИ</a></li>
      <li><a href="#comment">ОТЗЫВЫ </a></li>
      <li><a href="#video">ВИДЕО</a></li>
      <li><a href="#truck">ДОСТАВКА</a></li>
      
    </nav>

  </header>


  <section class="hero">
    <div class="background-image"  ></div>

    <div id="block_container_head">
  <div id="blochead1"><h1>АРМЕЙСКИЕ НАРУЧНЫЕ </br>ЧАСЫ AMST </h1>
    
  
    <h2 id="phone" >ЧАСЫ, КОТОРЫЕ ВЫБИРАЮТ</br>СИЛЬНЫЕ МУЖЧИНЫ</h2></div>

 

  <div id="blochead2">{% block content %}{% endblock %}</div>

</div>




 
    
  
    
 

    
    

    <div id='Label1' style='display: none;'>
    <a href="#call"> <wrapper>
  <div class="dws">
    <div class="pulse">
      <div class="bloc"></div>
      <div class="phone"><i class="fa fa-phone" aria-hidden="true"></i></div>
      <div class="text">Заказать звонок</div>
    </div>
  </div>
</wrapper> </a>
</div>
     
<script type='text/javascript'>

function isMobile(){if (navigator.userAgent.match(/Android|Mobile|IEMobile|Opera Mini|iPhone|iPad|iPod/i)==null)return false; else return true;}
    var label = isMobile();
    if (label==true) {
        document.getElementById("Label1").style.display='block';
                
    } else {
        document.getElementById("Label1").style.display='block';
        
    }
</script>

  </section>
  




  <section class="our-work" id="video">
   
     
    
<div id="block_container">
  <div id="bloc1"><iframe width="455" height="256" src="https://www.youtube.com/embed/vj1KrSdtv-o?rel=0&amp;showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe> 
    <a href="#call" class="button3">ЗАКАЖИТЕ СО СКИДКОЙ </a> </div>

 

  <div id="bloc2"><h1 class="title" ><h1>СДЕЛАЙ СЕБЕ 
МУЖСКОЙ ПОДАРОК</h1></br>Оригинальные НАРУЧНЫЕ ЧАСЫ AMST - новинка 2016 года и хит продаж. Уникальный военный дизайн, корпус из нержавеющей стали и стильный ремешок делают эти часы одними из самых популярных среди путешественников и искателей приключений по всему миру.</h2></br><h3></br>• БЫСТРАЯ ДОСТАВКА</br>
• ОПЛАТА ПРИ ПОЛУЧЕНИИ</br>
• 100% ГАРАНТИЯ КАЧЕСТВА!</h3></div>

</div>




</div>





  </section>
  

  <section class="features" id="special">

    
    
    
    <div id="block_container3">
  

  <div id="blocman1"><h1 class="title" ><h1>ЧАСЫ С МУЖСКИМ ХАРАКТЕРОМ!</h1></br><h2>AMST изготовлены из современных сверхпрочных материалов по специальной технологии и готовы к любой нагрузке.</h2></br></br><h3>• Часы AMST-3003 прошли в 2014 году сертификацию по военному стандарту MIL-PRF-46374G, тип 3, класс 1. Это свидетельствует о повышенной противоударности.</br></br>
• Часы антимагнитные, антикоррозийные, устойчивые к перепадам высот и температуры.</br>
</br>
• Испытаны на точность хода при стрельбе из автоматического оружия.</br></br>
• Официально поставляются в армейские подразделения ряда стран.</h3></div>

<div id="blocman2" class="gridman" ></div>

</div>
      
      


    
  </section>


  <section class="reviews" id="info">

    <div id="block_container4">
  

<div id="blocclock1" class="clock2" ></div>

  <div id="blocclock2"><h1 class="title" ><h1>ХАРАКТЕРИСТИКА ЧАСОВ AMST WATCH</h1></br><h2>AMST изготовлены из современных сверхпрочных материалов по специальной технологии и готовы к любой нагрузке.</h2></br></br><h3><i class="fa fa-check-square-o" aria-hidden="true">  Часы AMST-3003 прошли в 2014 году сертификацию по военному стандарту MIL-PRF-46374G, тип 3, класс 1. Это свидетельствует о повышенной противоударности.</i></br></br>
<i class="fa fa-check-square-o" aria-hidden="true"> Часы антимагнитные, антикоррозийные, устойчивые к перепадам высот и температуры.</i></br>
</br>
<i class="fa fa-check-square-o" aria-hidden="true"> Испытаны на точность хода при стрельбе из автоматического оружия.</i></br></br>
<i class="fa fa-check-square-o" aria-hidden="true"> Официально поставляются в армейские подразделения ряда стран.</i></h3></div>

</div>
    
  </section>




  <section id='grid' class="contact">
    <div id="block_container_warnning">
  

   <div id="blocwarnning1"><h1 class="title" ><h1><b>ВНИМАНИЕ!</b> ОСТЕРЕГАЙТЕСЬ ПОДДЕЛОК!</h1></br><h3>В связи с огромной популярностью часов AMST на рынке появилось много некачественных копий. Зачастую присылают дешевые китайские часы, которые Вам будет стыдно носить на руке, так как они напоминают оригинал лишь отдаленно.

Помните, что радость от низкой цены быстро сменяется горечью от некачественного изделия!

Хотите получить часы AMST превосходного качества? Обращайтесь к нам!</br></br>

<b>Наша компания является официальным партнером завода-изготовителя и владельца бренда AMST. Мы продаем оригинальные часы AMST уже более года и можем гарантировать Вам высочайшее качество и надежность часов.</b></h3></div>

<div id="blocwarnning2"  ></div>

</div>
         
  </section>


<section class="pole" id="pole">
   
    <div id="block_container5">
  

  <div id="blocpole1"><h1>НЕУБИВАЕМЫЕ АРМЕЙСКИЕ</br><b>
ЧАСЫ AMST</b></h1></br><h2>Сегодня скидка 50%!!</h2></br></br>
<h3><s>Старая цена: 1089 грн.</s></h3></br></br>
<h4>Новая цена: 549 грн.</h4></br>
</br>
</div>

<div id="blocpole2" >
 <h5> АКЦИЯ ОГРАНИЧЕНА</h5></br>
 <h3>до конца акции осталось</h3></br>
 <script src="http://megatimer.ru/s/91dd3eee3505b77001b4e34128151ec4.js"></script>
 
  

  <a href="#call" class="button3">ЗАКАЗАТЬ СЕЙЧАС</a> </div>
</div>

</div>
               
  </section>


<section id='grid' class="quastion">
  <h1>ПОЧЕМУ ПОКУПАТЕЛИ ДОВЕРЯЮТ ИМЕННО НАМ?</h1></br>
<h2>Более 1500 отправлений и довольных клиентов!</h2></br>

  <div id="block_container_quastion">
  
   <div id="blocquastion1">
   <h3><i class="fa fa-university" aria-hidden="true"></i> <b>Доступная цена.</b> У нас самые доступные цены на ОРИГИНАЛЬНЫЕ ЧАСЫ AMST, так как мы закупаем товар напрямую у производителя.</br></br>
   <i class="fa fa-percent" aria-hidden="true"></i> <b>Акции и праздничные скидки: до 50%! </b>за каждый заказанный экземпляр.</br></br>
   <i class="fa fa-credit-card" aria-hidden="true"></i> <b>Никакой предоплаты:</b> Вы оплачиваете ценную покупку в момент получения на почте или у курьера.</br></br></br>
   <i class="fa fa-smile-o" aria-hidden="true"></i> <b>Никаких расходов за формирование заказа.</b></br></br>
   <i class="fa fa-cube" aria-hidden="true"></i> <b>Мгновенное и качественное обслуживание:</b> отправка посылок два раза в день (включая выходные). SMS информирование покупателя о каждом статусе доставки.</br></h3>


   </div></br>

<div id="blocquastion2" ><h3>
   <i class="fa fa-truck" aria-hidden="true"></i> <b>Быстрая доставка:</b>  в любую точку Украины за 1-2 дня (в зависимости от региона).</br></br>
  <i class="fa fa-gift" aria-hidden="true"></i> <b> Подарки постоянным клиентам</b></br></br>
  <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> <b>Знаменитый бренд:</b> однозначно поднимает самооценку и создает достойный имидж.</br></br>
  <i class="fa fa-check-circle" aria-hidden="true"></i> <b>Гарантии на товар.<b> Перед отправкой товары проходят 100% проверку.</br></br>
  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> <b>Мы работаем, опираясь на букву закона<b></br></h3>

</div>

</div>




        
<section id='comment' class="comment">
 
  <h1>ОТЗЫВЫ ПОКУПАТЕЛЕЙ</h1>

<div id="block_container_comment">
  
  
  

</div>



<div id="block_container_comment">
<div id="bloccomment1_1">
  <div id="bloccomment1"></div>
   Ольга Потапова</br></br>
<h3>Часы супер, подарок удался, супруг доволен. Все соответствует как на фото. Спасибо за своевременность- посылка пришла очень быстро. Советую всем, кто хочет приобрести себе такие часики!</h3>

   </div>
   <div id="bloccomment2_1">
    <div id="bloccomment2" ></div>
   Александр Новиков</br></br>
<h3>Спасибо за быструю доставку. Часы просто супер, идут секунда в секунду и при этом очень стильно смотрятся.</h3>

   </div>
   <div id="bloccomment3_1">
    <div id="bloccomment3" ></div>
   Алексей Мингалёв</br></br>
<h3>Ношу часы уже третий месяц,один раз уронил их с подоконника, думал всё, ничего подобного всё работает, стекло оказалось крепкое. На вид часы лучше чем на картинке, ярче и больше. Кожаный ремешок удобный и приятный на ощупь. Спасибо за классные часы!</h3>

   </div></div>
</section>




<section id='work' class="work">
 
  <h1>КАК МЫ РАБОТАЕМ</h1>

  <ul class="grid">
   
    <li> <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      <h3>ЗАЯВКА</h3></br>
Оставьте заявку на сайте - для этого укажите Ваше имя и номер телефона</li>
    <li><i class="fa fa-volume-control-phone" aria-hidden="true"></i>
      <h3>ОФОРМЛЕНИЕ ЗАКАЗА</h3></br>
Наш менеджер свяжется с Вами для уточнения деталей и оформит заказ</li>
    <li><i class="fa fa-truck" aria-hidden="true"></i>
      <h3>ДОСТАВКА</h3></br>
Мы отправим посылку в этот же день 1-м классом Новой почтой или курьером (От пожелания клиента)</li>
    <li><i class="fa fa-cube" aria-hidden="true"></i>
      <h3>ПОЛУЧЕНИЕ</h3></br>
Вы получите извещение о доставке и сможете забрать посылку в ближайшем отделении Новой Почты или у курьера</li>
  </ul>
  
</section>



<section id='truck' class="truk">
  <h2>ДОСТАВКА И ОПЛАТА</h2></br>
 <h3>ДОСТАВКА ПО Украине</h3>
<h4>Мы вам доверяем и не требуем с вас предоплаты. Все заказы отправляются посылками с объявленной ценностью. Вы можете забрать и оплатить свои новые часы в любое удобное для вас время в Вашем почтовом отделении или у курьера.</h4></br>


 <h3>СРОКИ ДОСТАВКИ</h3>
<h4>Мы отправим ваш заказ уже сегодня. Товар отправляется картонных коробках. Часы дойдут до вас быстро и без единой царапинки. Доставка займет 1-2 рабочих дней. Чтобы ускорить прибытие вашего заказа, мы отправляем посылки два раза в день, включая выходные дни.</h4></br>


 <h3>ОПЛАТА ЗАКАЗА НАЛОЖЕННЫМ ПЛАТЕЖОМ</h3>
<h4>Оплата осуществляется курьеру или в отделении Новой Почты при получении заказа.</h4>
</section>





  <section class="sale2" id="sale2">
    <h1 >РАБОТАЕМ ЧЕСТНО. ГАРАНТИИ </h1></br></br>

    <ul class="grid">
   
    <li> 
      <h10>КАЧЕСТВЕННЫЙ ТОВАР</h10></br>
      <img src="{% static 'assets/css/assets/img/100.jpg' %}" ></br>
Перед отправкой товары тщательно проверяются вручную. Мы работаем только с официальными поставщиками и всегда в первую очередь думаем о своих клиентах.</li>
    
    <li>
      <h10>ОПЛАТА ПРИ ПОЛУЧЕНИИ</h10></br>
      <img src="{% static 'assets/css/assets/img/101.jpg' %}" ></br>
Мы не берем с вас предоплату. Оплата заказа осуществляется при получении в почтовом отделении, в пункте самовывоза или в руки курьеру после проверки товара.</li>

    <style type="text/css">.sale2 h11{
  font: bold 40px 'Open Sans', sans-serif;
  margin-bottom:7%;
  text-shadow: 0 0 5px #000;
  margin-right: 70%;
  text-align: left;

  
}

.sale2 h12{
  font: normal 17px 'Open Sans', sans-serif;
  margin-bottom:10%;
  text-shadow: 0 0 10px rgb(255, 255, 255);
  margin-right: 60%;
  text-align: left;
  color: black;
   padding-left: 25px;

}
.sale2 h13{
  margin-bottom: 10px;
  font: normal 35px 'Open Sans', sans-serif;
  text-shadow: 0 0 10px red;
  text-align: center;
  color: white;
  padding-left: 25px;
  

}


.sale2 h15{
  font: normal 14px 'Open Sans', sans-serif;
  margin-top: 20px;
  
  text-align: center;
}
.sale2 h16{
    margin-bottom: 10px;
  font: bolder 40px 'Open Sans', sans-serif;
  text-shadow: 0 0 10px red;
  text-align: center;
} 
 
</style>
<div class="form">

    <form id="call"  action="/contact/" method="post">{% csrf_token %}

    {{ form.non_field_errors }}
    <div class="row"  >
    <div class="col-md-4 col-md-offset-4" >
     
      <h13>ОСТАВЬТЕ ЗАЯВКУ</h13> </br></br>
      <h12>Прямо сейчас и получите часы AMSTсо скидкой 50%!</br></br></h12>

      <div class="newprice">
        <div id="block_container2">
          <div id="bloctop1"><h15>Обычная цена:</h15></br><h14><s>1098 грн.</s></h14></div>
          <div id="bloctop2"><h15>Цена по акции:</h15></br><h16>549грн</h16>
</div></div></div>

      <!--Timer !-->
    <script src="http://megatimer.ru/s/fd1e89200e0c3e546beac2ca35a6d55e.js"></script>
  </br>
      <label for="id_subject">Имя:</label>
      {{ form.subject.errors }}
      {{ form.subject }}
    </div></div>

    

    <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <label for="id_message">Телефон:</label>
      {{ form.message.errors }}
      {{ form.message }}
    </div></div>
</br>
      <input name="submit" class="btn" type="submit" value="ЗАКАЗАТЬ"/>
    </div></div>
</form></div>
</div>
  </ul>
    
    

        
  </section>


  <footer>
   
    <p>АРМЕЙСКИЕ НАРУЧНЫЕ ЧАСЫ AMST </p>
    
    
  </footer>

</body>

</html>

newitem/templates/base_generic2.html
<!doctype html>

<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-127165440-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-127165440-1');
</script>

  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="css/styles.css?v=1.0">

  <!--[if lt IE 9]>
 <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
     {% block content %}{% endblock %}
  <script src="js/scripts.js"></script>
</body>
</html>

newitem/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <ul>
    <li><strong>Books:</strong> {{ price }}</li>
    <li><strong>Copies:</strong> {{ oldprice }}</li>
    <li><strong>Authors:</strong> {{ discount }}</li>
  </ul>
{% endblock %}

newitem/templates/templates/contact.html
{% extends 'base_generic.html' %}

{% block content %}

<form  action="/contact/" method="post">{% csrf_token %}

    {{ form.non_field_errors }}
    <div class="row"  >
    <div class="col-md-4 col-md-offset-4" >
     
      <h3>ОСТАВЬТЕ ЗАЯВКУ</h3> </br>
      <h4>Прямо сейчас и получите часы AMSTсо скидкой 50%!</br></h4>

      <div class="newprice">
        <div id="block_container2">
          <div id="bloctop1"><h5>Обычная цена:</h5></br><h4><s>1098 грн.</s></h4></div>
          <div id="bloctop2"><h5>Цена по акции:</h5></br><h6>549грн</h6>
</div></div></div>

      <!--Timer !-->
    <script src="http://megatimer.ru/s/fd1e89200e0c3e546beac2ca35a6d55e.js"></script>
  </br>
      <label for="id_subject">Имя:</label>
      {{ form.subject.errors }}
      {{ form.subject }}
    </div></div>

    

    <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <label for="id_message">Телефон:</label>
      {{ form.message.errors }}
      {{ form.message }}
    </div></div>
</br>
      <input name="submit" class="btn" type="submit" value="ЗАКАЗАТЬ"/>
    </div></div>
</form>

{% endblock %}

newitem/templates/templates/contact2.html
{% extends 'base_generic.html' %}

{% block content2 %}

<form action="/contact/" method="post">{% csrf_token %}

    {{ form.non_field_errors }}
    <div class="row"  >
    <div class="col-md-4 col-md-offset-4" >
     
      <h4>До конца акции осталось!:</h4> </br>
      <!--Timer !-->
    <script src="http://megatimer.ru/s/fd1e89200e0c3e546beac2ca35a6d55e.js"></script>
  </br>
      <label for="id_subject">Имя:</label>
      {{ form.subject.errors }}
      {{ form.subject }}
    </div></div>

    

    <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <label for="id_message">Телефон:</label>
      {{ form.message.errors }}
      {{ form.message }}
    </div></div>
</br>
      <input name="submit" class="btn" type="submit" value="ЗАКАЗАТЬ"/>
    </div></div>
</form>

{% endblock %}

newitem/templates/templates/thanks.html
{% extends 'base_generic2.html' %}

{% block content %}
<style type="text/css">
	.thanks{
	text-align: center;
	background-color: rgb(35, 237, 237);

	h1{
	color: #414a4f;
	font: bold 40px 'Open Sans', sans-serif;
	text-transform: capitalize; 
	padding-bottom: 40px;
	text-align: center;
	}
}


</style>
<div class="thanks">
<div class="row">
    <div class="col-md-4 col-md-offset-4">
      


<h1>Спасибо за Ваш заказ!</h1></br><hr>
<h2>В течении 5-10 минут вам перезвонит наш менеджер.</h2></br>
<h2>Если вы ошиблись при заполнении формы, то, пожалуйста,<a href="{% url 'contact' %}"> заполните заявку еще раз.</a></h2>
<footer>
   
    <p>
    ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ
</br>

Наш интернет-магазин уважительно относится к правам клиента. Соблюдается строгая конфиденциальность при оформлении заказа. Сведения надёжно сохраняются и защищены от передачи.

Согласием на обработку данных клиента исключительно с целью оказания услуг является размещение заказа на сайте.



</p>
    
  </footer>

</div></div></div>


{% endblock %}